name: Lagrange.OneBot Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runtimeIdentifier:
          [
            win-x64,
            win-x86,
            linux-x64,
            linux-arm,
            linux-arm64,
            osx-x64,
            osx-arm64,
            linux-musl-x64,
            linux-musl-arm,
            linux-musl-arm64,
          ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet publish Lagrange.OneBot/Lagrange.OneBot.csproj --self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=none -p:RuntimeIdentifier=${{ matrix.runtimeIdentifier }} --framework net8.0

      - run: zip -r Lagrange.OneBot_${{ matrix.runtimeIdentifier }}_net8.0_SelfContained.zip ./Lagrange.OneBot/bin/Release/net8.0/${{ matrix.runtimeIdentifier }}/publish

      # - uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: nightly-test
      #     name: Nightly Release Test
      #     prerelease: true
      #     body: "> ⚠️This is a nightly release.\n> ⚠️This is not the latest version."
      #     files: Lagrange.OneBot_${{ matrix.runtimeIdentifier }}_net8.0_SelfContained.zip
      #     token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ncipollo/release-action@v1
        with:
          tag: nightly
          name: "Nightly Release"
          prerelease: true
          body: "> ⚠️This is a nightly release.\n> ⚠️This is not the latest version."
          artifacts: Lagrange.OneBot_${{ matrix.runtimeIdentifier }}_net8.0_SelfContained.zip
          allowUpdates: true
          removeArtifacts: true