name: Lagrange.Core NuGet Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    types:
      - closed
    branches: [ "master" ]

jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100

      - name: Build and Pack
        run: |
          cd ./Lagrange.Core
          dotnet build --configuration Release
          dotnet pack --configuration Release
          dotnet pack --configuration Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
          ls
          ls ./bin/Release/

      - name: Install Nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'

      - name: Add private GitHub registry to NuGet
        if: ${{ !github.head_ref }}
        run: |
          dotnet nuget add source --username Linwenxuan05 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/LagrangeDev/index.json"

      - name: Push generated package to GitHub registry and NuGet
        if: ${{ !github.head_ref }}
        run: |
          dotnet nuget push .\Lagrange.Core\bin\Release\*.nupkg --source "github" --api-key ${{ secrets.GIT_TOKEN }}
          nuget push .\Lagrange.Core\bin\Release\*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -ApiKey ${{ secrets.NUGETAPIKEY }}
